spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pleasant?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ssafy
    password: ssafy
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  data:
    redis:
      host: localhost
      port: 6379

  output:
    ansi:
      enabled: always

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    enabled: true
logging:
  level:
    org:
      springframework:
        web: debug


