server:
  port: 8080
logging:
  level:
    web: debug
    sql: debug

spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payment?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root

    jpa:
      show-sql: false
      properties:
        hibernate:
          format_sql: true
      database: mysql
      hibernate:
        ddl-auto: create

---
spring:
  config:
    activate:
      on-profile: stage
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payment?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root

    jpa:
      show-sql: false
      properties:
        hibernate:
          format_sql: true
      database: mysql
      hibernate:
        ddl-auto: create
